### PR TITLE
ircclient: Handle ready_for_review and converted_to_draft

### PR DESCRIPTION
**Pull request by Pokechu22**

### CODE REVIEW

**Comment by Pokechu22** [comment]
There is also an event for converting to draft (see events for [this repo](https://api.github.com/repos/dolphin-emu/sadm/issues/events), specifically when I [marked this PR as a draft](https://api.github.com/repos/dolphin-emu/sadm/issues/events/3224554791) and then [marked as ready for review](https://api.github.com/repos/dolphin-emu/sadm/issues/events/3224554954), namely `convert_to_draft`.  However, irrawaddy doesn't seem to have noticed it, and it's not mentioned [in the API docs](https://developer.github.com/v3/activity/events/types/#pullrequestevent), so probably it doesn't need to be handled yet.

**Comment by Pokechu22** [comment]
The new developer documentation now has both [`ready_for_review`](https://docs.github.com/en/developers/webhooks-and-events/issue-event-types#ready_for_review) and [`convert_to_draft`](https://docs.github.com/en/developers/webhooks-and-events/issue-event-types#convert_to_draft).  When I [marked this PR as draft again](https://api.github.com/repos/dolphin-emu/sadm/issues/events/3663003128) and then [unmarked it](https://api.github.com/repos/dolphin-emu/sadm/issues/events/3663003514), however, irrawaddy said it was <code>convert<ins>ed</ins>_to_draft</code> and `ready_for_review` respectively.  I don't know where that `ed` came from, but at least it's noticing it now...

**Review by Dentomologist — COMMENTED** [review]
The developer documentation now says converted_to_draft, so I suppose it was just out of date at the time. Did you omit that case deliberately, or was it just the uncertainty about the documentation?

**Comment by Pokechu22** [comment]
I initially omitted it because the docs didn't mention it at all, and then because of uncertainty.  At this point it should be fine to change it.

It does seem like the "[Issue event types](https://docs.github.com/en/developers/webhooks-and-events/events/issue-event-types#convert_to_draft)" documentation still says `convert_to_draft` but "[Webhook events and payloads](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#webhook-payload-object-33)" says `converted_to_draft`.

**Review by Dentomologist — APPROVED** [review]

**Pull request merged**
