### PR TITLE
buildbot: switch to CMake+Ninja for Windows builds

### PR DESCRIPTION
**Pull request by leoetlino**
Finishes the CMake migration.

Unlike #113 (the previous attempt), this PR takes a different approach. Instead of assuming that the compiler and environment variables are already set, we call the vcvars64.bat batch script to find the WinSDK, compiler path, include paths, etc. and to set any environment variables that are required to compile.

This should require less maintenance than the previous approach. The only time we have to change something in the buildbot config file is when we upgrade to a new major version of Visual Studio.

One concern that was raised last time is that the WinSDK version is not pinned so we end up using the latest WinSDK version.
However, since https://github.com/dolphin-emu/dolphin/pull/8498 was merged, the VS project files also do the exact same thing, and minimum version checks have been added elsewhere to ensure the WinSDK version isn't too old.

Anyway, with this approach, if we ever need to use a specific version of the Windows SDK, we can easily switch to vcvarsall.bat later on: https://docs.microsoft.com/en-us/cpp/build/building-on-the-command-line?view=msvc-160#vcvarsall-syntax so I don't think this should be a blocker.

I've tested the build steps I added in a Windows VM, but this needs some testing to make sure e.g. incremental builds work fine *on the builder*.

### CODE REVIEW

**Comment by leoetlino** [comment]
The latest version of this PR requires dolphin-emu/dolphin#9649 and dolphin-emu/dolphin#9650. I've tested locally that the binaries end up in the right folder and that the auto-updater is now enabled by default.

**Comment by stenzek** [comment]
Probably should do some performance testing on the cmake builds before merging - if I remember correctly, msbuild's defaults had different cflags vs cmake. Plus no symbols in Release builds, and RelWithDebInfo disables a bunch of stuff like inlining.

**Comment by JMC47** [comment]
After spending a good part of the day running tests on different flag configurations, we've gotten the cmake builds performing identical to Master.  The performance tests on the last batch were within error, trending *slightly* faster than master, but I really do believe that they're identical and it was just some random variation.

**Comment by shuffle2** [comment]
please do not switch to cmake until the msvc flags exactly match what is currently in msbuild.

cmake/ninja has the downside that it does not perform batching of source files to the compiler, which is a minor speed boost for msvc. I've brought it up with cmake and they say it's ninja's problem (idk): https://discourse.cmake.org/t/using-cmake-ninja-to-batch-cl-invocations/1853/8 but haven't followed up with ninja.

I don't think cmake is an improvement over msbuild, but I understand other people want it. I at least don't want to see regressions in the resulting output from this switch.

**Comment by JMC47** [comment]
Last I checked, we had everything identical performance wise.  I don't know if that means every flag is identical.

**Pull request closed without merging**
