### PR TITLE
buildbot: use ninja on the Linux buildslaves

### PR DESCRIPTION
**Pull request by Tilka**
It's already installed on the Debian buildslave.

### CODE REVIEW

**Comment by delroth** [comment]
Do we also have it on the ubuntu buildbot? It shares this builder configuration.

**Comment by delroth** [comment]
@Parlane can probably confirm.

**Comment by Parlane** [comment]
It wasn't installed, it is now. Any other dependencies required?

**Comment by Tilka** [comment]
@Parlane No.

**Comment by phire** [comment]
Looks like you forgot the nvidia fifoci

**Pull request merged**
