### PR TITLE
buildbot: Automatically generate baseline profiles

### PR DESCRIPTION
**Pull request by t895**
This adds two new commands to the Android buildbot where it generates the baseline-prof.txt file using a gradle managed device, and then copies the result into the project where the profile installer can see it.

Note - This PR depends on dolphin-emu/dolphin#11411 being merged first.

### CODE REVIEW

**Comment by delroth** [comment]
Can you describe a bit more what that does and why it's desirable?

**Comment by t895** [comment]
Baseline profiles are explained in #11335 and this addition to the buildbot allows the profile to stay up to date with the changing libraries used in the app. Given that we use more libraries in the future, the app will continue to see performance improvements. (I mean the UI not emulation speed)

**Comment by delroth** [comment]
Thanks. Out of curiosity, how much of this could be done via Gradle instead of adding more ad-hoc build steps? I'd rather move more complexity into the build system rather than have the complexity into the buildbot recipes.

**Comment by t895** [comment]
> Thanks. Out of curiosity, how much of this could be done via Gradle instead of adding more ad-hoc build steps? I'd rather move more complexity into the build system rather than have the complexity into the buildbot recipes.

I'll look around but afaik there isn't a way to do this without stringing together a bunch of commands like this.

**Comment by t895** [comment]
Ok, looking through the official codelabs and documentation, there is currently no way to have gradle copy the baseline profile into the right directory. Gradle also doesn't let you combine the build and baseline profile generation commands. It's not great, but baseline profiles are pretty new.

I also just checked to see if the [incremental build bug](https://issuetracker.google.com/issues/232060576) was fixed... still no response.

**Comment by Pokechu22** [comment]
Can't you just use a [Copy task](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.Copy.html)?

**Comment by t895** [comment]
Ok, unless I'm wrong again, there isn't a reasonable way of running a gradle task in the benchmark module from the app module or the top level build.gradle file. I managed to figure out how to get the copy task working though. If there's no baseline profile, it will just silently fail as shown in [#11420](https://github.com/dolphin-emu/dolphin/pull/11420). I've also moved generation of the profile to release builds only because it can be a very lengthy build step and being a debug build will already outweigh the performance improvements that a profile can provide.

**Comment by Pokechu22** [comment]
You can write `project(':app').evaluationDependsOn(':benchmark')`, but I don't think that would be compatible with doing it only for the release build, and I don't think you can do a task dependency across projects (probably, at least), nor can you specify the `-P android.testInstrumentationRunnerArguments.androidx.benchmark.enabledRules=BaselineProfile` part.

**Comment by t895** [comment]
> You can write `project(':app').evaluationDependsOn(':benchmark')`, but I don't think that would be compatible with doing it only for the release build, and I don't think you can do a task dependency across projects (probably, at least), nor can you specify the `-P android.testInstrumentationRunnerArguments.androidx.benchmark.enabledRules=BaselineProfile` part.

Well I wouldn't know how to pass arguments there. It doesn't seem possible to me.

**Pull request closed without merging**
