### PR TITLE
IRC: Ignore "comment edited/deleted" events

### PR DESCRIPTION
**Pull request by leoetlino**
This makes the IRC bot ignore PR comment edited or deleted events.

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/sadm/61)

### CODE REVIEW

**Comment by delroth** [comment]
pull_request_comment events don't have an action field:

    2016-06-18T21:46:42.161515	{'source': 'ghhookparser', 'url': 'https://github.com/dolphin-emu/dolphin/pull/3905#discussion_r67607062', 'hash': 'ae31c964741c26bda9b118cc76f3f8d7482f42d8', 'type': 'gh_pull_request_comment', 'repo': 'dolphin-emu/dolphin', 'author': 'phire', 'id': 3905}

**Comment by phire** [comment]
I think it's useful to have "X edited their comment" notifications. the main problem is they currently show up as "Commented" which is confusing.

**Comment by leoetlino** [comment]
Are you sure about that? I tested it and GH did send events with an `action` field. What you sent seems to be a log entry, is that right? If so, I think it's normal that it doesn't show up there, because while it's being sent by GitHub, we're currently not using it at all.

**Comment by delroth** [comment]
Duhh nevermind, you're right, wrong log.

**Pull request merged**
