### PR TITLE
central: link GitHub comments to YouTrack issues

### PR DESCRIPTION
**Pull request by Tilka**
~~Totally untested due to lack of laptop.~~
Tested and seems to work~~, although the regex needs to be tweaked to not replace already linked issue references~~.

### CODE REVIEW

**Comment by BhaaLseN** [comment]
Is this "YouTrack comment on issue" to "GitHub comment on PR"? How do you map Issues to PRs?

**Comment by Tilka** [comment]
I guess the commit message is a bit ambiguous. It replaces "XYZ-123" with "[XYZ-123](http://issues.dolphin-emu.org/youtrack/issue/XYZ-123)" in GitHub comments.

**Comment by linkmauve** [comment]
Since YouTrack isn’t going to be used, you should close this PR.

**Comment by delroth** [comment]
However I wish we had something like that for our Redmine issues :) So maybe don't?

**Pull request closed without merging**
